### ISSUE TITLE
ModuleNotFoundError: No module named 'pygame'

### ISSUE THREAD

**Issue by drumplayer1234** [loseys/BlackMamba#13]
┌──(kali㉿kali)-[~/BlackMamba]
└─$ sudo python3 main.py
Traceback (most recent call last):
  File "/home/kali/BlackMamba/main.py", line 29, in <module>
    from clientui.app_modules import *
  File "/home/kali/BlackMamba/clientui/app_modules.py", line 9, in <module>
    from clientui.ui_main import Ui_MainWindow
  File "/home/kali/BlackMamba/clientui/ui_main.py", line 14, in <module>
    from clientui.vstrm_server import *
  File "/home/kali/BlackMamba/clientui/vstrm_server.py", line 17, in <module>
    import pygame
ModuleNotFoundError: No module named 'pygame'

**Comment by kosherroach** [comment]
Same problem here. 
Another issue occurred when pip install -r requirements.txt.
"error: metadata-generation-failed"

**Comment by CamoCatX** [comment]
@kosherroach @drumplayer1234 Do this command: python3 -m pip install pygame Tell me if that does not work.

**Comment by 20LeoiX** [comment]
smartest kali user

**Comment by Maddox1211** [comment]
> smartest kali user
onb they be flexing that they on kali then cant install pygame 🤣🤣
