### ISSUE TITLE
ModuleNotFoundError: No module named 'pyautogui'

### ISSUE THREAD

**Issue by apollxo** [loseys/BlackMamba#14]
sudo python3 main.py  
                                                                                                       
Traceback (most recent call last):
  File "/home/umidevop/Spyware/BlackMamba/main.py", line 30, in <module>
    from clientui.app_modules import *
  File "/home/umidevop/Spyware/BlackMamba/clientui/app_modules.py", line 9, in <module>
    from clientui.ui_main import Ui_MainWindow
  File "/home/umidevop/Spyware/BlackMamba/clientui/ui_main.py", line 15, in <module>
    from clientui.control import *
  File "/home/umidevop/Spyware/BlackMamba/clientui/control.py", line 24, in <module>
    import pyautogui
ModuleNotFoundError: No module named 'pyautogui'

**Comment by ghost** [comment]
Did you run `python3 -m pip install -r requirements.txt`?

Also make sure all python command are run in the same environment.

**Comment by apollxo** [comment]
it didn't work,but i found the other way to solve. but thanks a lot
